// src/views/Home.vue
<template>
  <main class="home">
    <Message title="Felipe Azevedo Bosi" text="Frontend developer specialized in solutions for educational and health care systems." />
    <b-container class="social">
      <b-row>

        <b-col md="3" cols="6">
          <a href="https://github.com/bosifullstack"><i class="nes-icon github is-large" title="GitHub"></i></a>
        </b-col>

        <b-col md="3" cols="6">
          <a href="https://www.linkedin.com/in/felipebosi/"><i class="nes-icon linkedin is-large" title="LinkedIn"></i></a>
        </b-col>

        <b-col md="3" cols="6">
          <a href="https://twitter.com/bosiarquitetura"><i class="nes-icon twitter is-large" title="Twitter"></i></a>
        </b-col>

        <b-col md="3" cols="6">
          <a href="mailto:bosifullstack@gmail.com"><i class="nes-icon gmail is-large" title="Email"></i></a>
        </b-col>

      </b-row>
    </b-container>

    <Lists 
      title="Main open-source projects" 
      description="Here are my main open-source projects. You can see the rest of them on my GitHub account."
      :items="openSourceItems"
    />

    <Lists 
      title="Work experiences" 
      description="Here you can see some of the private projects that I made or participate on the main developer team."
      :items="workExperiencesItems"
    />

  </main>
</template>

<script lang="ts">
import { Component, Vue } from 'vue-property-decorator';

// @ is an alias to /src
import Message from '@/components/Message.vue'
import Lists from '@/components/Lists.vue'

@Component({
  components: {
    Message,
    Lists,
  }
})

export default class Home extends Vue{
  private openSourceItems: Array<object> = [
    {title: "StartPage", link: "https://github.com/bosifullstack/startpage", description: "A PWA StartPage made with vanilla javascript"},
    {title: "React FakeStore", link: "https://bosifullstack.github.io/fakeStore/", description: "A fake store website made with React and Redux"},
    {title: "Get Stock", link: "https://github.com/bosifullstack/cotacoes", description: "A website that get data of a stock from an API"},
    {title: "To-Do CLI", link: "https://github.com/bosifullstack/ToDo-CLI", description: "A ToDo list CLI app made with Node.js"},
  ]

  private workExperiencesItems: Array<object> = [
    { title: "Chen Tai Chi Brasil", link: "https://chentaichibrasil.com/", description: "Main developer of the website. Made on Wordpress, its purpose is to be a plataform for the Brazilian Chen Tai Chi community" },
    { title: "UVV", link: "https://www.uvv.br/", description: "Part of the front-end team responsable to maintain the site running" },
    { title: "Phidelis", link: "https://phidelis.com.br/", description: "Part of the front-end/design team. Responsable for the implementation of Vue.js and Nuxt.js on the product." },
    { title: "Foca Enem", link: "https://focaenem.folhavitoria.com.br/", description: "Part of the front-end/design team responsable refactor all of the product" },
  ]
}
</script>

<style lang="scss">
.social {
  text-align: center;
  padding: 60px 0;
  }
</style>

// src/routes/home.svelte
<script lang="ts">
  import Message from "../components/atoms/Message.svelte";
  import SocialSection from "../components/atoms/SocialSection.svelte";
  import ListWithLinks from "../components/molecules/ListWithLinks.svelte";
  import StarsList from "../components/molecules/StarsList.svelte";
  import type { itemProps } from "../components/atoms/ItemWithDescription.type";
  import type { starType } from "../components/molecules/StarsList.type";

  const openSourceItems: itemProps[] = [
    {
      title: "StartPage",
      link: "https://github.com/bosifullstack/startpage",
      description: "A PWA StartPage made with svelte",
    },
    {
      title: "React FakeStore",
      link: "https://bosifullstack.github.io/fakeStore/",
      description: "A fake store website made with React and Redux",
    },
    {
      title: "Get Stock",
      link: "https://github.com/bosifullstack/cotacoes",
      description: "A website that get data of a stock from an API",
    },
    {
      title: "To-Do CLI",
      link: "https://github.com/bosifullstack/ToDo-CLI",
      description: "A ToDo list CLI app made with Node.js",
    },
  ];
  const workExperiencesItems: itemProps[] = [
    {
      title: "Luma Health",
      link: "https://www.lumahealth.io/",
      description:
        "Main developer of the blog and part of the frontend team responsible from the company's app. The blog is made in Wordpress and the app is in React",
    },
    {
      title: "UVV",
      link: "https://www.uvv.br/",
      description:
        "Part of the front-end team responsible to maintain the site running",
    },
    {
      title: "Phidelis",
      link: "https://phidelis.com.br/",
      description:
        "Part of the front-end/design team. Responsable for the implementation of Vue.js and Nuxt.js on the product.",
    },
    {
      title: "Foca Enem",
      link: "https://focaenem.folhavitoria.com.br/",
      description:
        "Part of the front-end/design team responsable refactor all of the product",
    },
  ];

  const programmingLanguages: starType[] = [
    {
      title: "Java",
      stars: 3,
    },
    {
      title: "NodeJs",
      stars: 3,
    },
    {
      title: "JavaScript",
      stars: 5,
    },
    {
      title: "TypeScript",
      stars: 4,
    },
    {
      title: "PHP",
      stars: 2,
    },
  ];

  const frameworks: starType[] = [
    {
      title: "String Boot",
      stars: 3,
    },
    {
      title: "ExpressJs",
      stars: 3,
    },
    {
      title: "SvelteJs",
      stars: 4,
    },
    {
      title: "React",
      stars: 4,
    },
  ];
</script>

<style>
  .section-title {
    margin-bottom: 1.5em;
  }
  @media (max-width: 768px) {
    .flex {
      flex-wrap: wrap;
    }
  }
</style>

<div class="container">
  <Message
    title={'Felipe Azevedo Bosi'}
    text={'Frontend developer specialized in solutions for educational and health care systems.'} />
  <SocialSection />
  <ListWithLinks
    title="Main open-source projects"
    description="Here are my main open-source projects. You can see the rest of them on my GitHub account."
    items={openSourceItems} />
  <ListWithLinks
    title="Work experiences"
    description="Here you can see some of the private projects that I made or participate on the main developer team."
    items={workExperiencesItems} />

  <article class="container">
    <div class="lists">
      <h1 class="section-title">Programming Abilities</h1>
      <div class="flex">
        <StarsList title="Programming Languages" stars={programmingLanguages} />
        <StarsList title="Frameworks" stars={frameworks} />
      </div>
    </div>
  </article>
</div>
