// src/components/atoms/Message.svelte
<script lang="ts">
  export let title: string;
  export let text: string;
</script>

<style>
  .message__text {
    text-align: left;
  }
  @media (min-width: 768px) {
    .message__title {
      font-size: 24px !important;
    }
  }
</style>

<div class="nes-container is-dark message {title && 'with-title'}">
  <p class="title message__title">{title}</p>
  <p class="message__text">{text}</p>
</div>

// src/components/Message.vue
<template>
  <b-container>
    <div class="container nes-container is-dark message" :class="withTitle">
      <p class="title message__title">{{ title }}</p>
      <p class="message__text">{{ text }}</p>
    </div>
  </b-container>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';

@Component
export default class Message extends Vue {
  @Prop(String) private title!: string;
  @Prop(String) private text!: string;

  private withTitle: string = (this.title !== '') ? 'with-title' : '';
}
</script>

<style lang="scss">
.message {
  &__title {
    @media (min-width: 768px) {
      font-size: 24px !important;
    }
  }
  &__text {
    text-align: left;
  }
}
</style>
